name: Export GitHub Repos to CSV

on:
  workflow_dispatch:  # spustíš ručně z GitHub UI
  schedule:
    - cron: "0 6 * * 1"  # volitelné: každé pondělí v 6:00 UTC

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install GitHub CLI and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y gh jq

      - name: Authenticate GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh auth login --with-token <<< "$GITHUB_TOKEN"

      - name: Fetch repos and save to CSV
        run: |
          gh repo list PajaspaceNet --limit 200 --json name,description,url \
            | jq -r '.[] | [.name, (.description // ""), .url] | @csv' > repos.csv

      - name: Commit CSV
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add repos1.csv
          git commit -m "Update repo list [skip ci]" || echo "No changes to commit"
          git push
